# Numpy

## Zeros and Ones

![](imgs\zeros_and_ones_1.png)
![](imgs\zeros_and_ones_2.png)

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import numpy as np

# Read the input as a string, split it to get a list. Then convert 
# each list element to int with map. Finally, convert the map into a tuple as the first parameter of zeros an ones is a tuple
number_tuple = tuple(map(int, input().split()))

# create the ndarray using int as a datatype
print(np.zeros(number_tuple, dtype = np.int))
print(np.ones(number_tuple, dtype = np.int))

## Eye and Identity

![](imgs\eye_and_identity_1.png)
![](imgs\eye_and_identity_2.png)

In [2]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import numpy as np

# We get the number of rows and columns from stdin
n, m = map(int, input().split())
np.set_printoptions(legacy='1.13')

# As the matrix is nxm we use numpy.eye
print(np.eye(n, m))

1


ValueError: not enough values to unpack (expected 2, got 1)

## Concatenate

![](imgs\concatenate_1.png)
![](imgs\concatenate_2.png)

In [7]:
import numpy

array_1 = numpy.array([[1,2,3],[0,0,0]])
array_2 = numpy.array([[1,1,1],[7,8,9]])

print(array_1)
print(array_2)
print(numpy.concatenate((array_1, array_2), axis = 1)) # The array is extended to the right
print(numpy.concatenate((array_1, array_2), axis = 0)) # The array is extended to the bottom 

[[1 2 3]
 [0 0 0]]
[[1 1 1]
 [7 8 9]]
[[1 2 3 1 1 1]
 [0 0 0 7 8 9]]
[[1 2 3]
 [0 0 0]
 [1 1 1]
 [7 8 9]]


In [8]:
print(numpy.array([[1, 2], [1,2], [1,2]]))

[[1 2]
 [1 2]
 [1 2]]


In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
# IMPORTANT NOTE. No error handling is implemented. The code below passes all tests needed to be accepted as a right answer
import numpy as np

# The input is read and unpacked into variables n (rows first array), m (rows second array) and p (columns)
n, m, p = map(int, input().split())

# We read the N rows of the first array using input. Each input is then read as string. We use split to get the P elements corresponding with each column as a list. Using map we transform each element to int and then convert the map into a list. That list represents the final row. Finally we append the row to a list. The array is created from the list of rows
rows = []
for _ in range(n):
    rows.append(list(map(int, input().split())))
array_1 = np.array(rows)

# We repeat the same logic to create the second array
rows = []
for _ in range(m):
    rows.append(list(map(int, input().split())))
array_2 = np.array(rows)

# Finally, we concatenate the previous arrays along the first dimension to get the desired result
print(np.concatenate((array_1, array_2), axis = 0))

## Array Mathematics

![](imgs\array_mathematics_1.png)
![](imgs\array_mathematics_2.png)

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import numpy as np

# The number of rows and columns are read from the input as usual
n, m = list(map(int, input().split()))

# We use a for loop to read n lines from input. Each line will contain M elements. As we use input, firstly we need to convert the string read into a list containing the elements. Secondly, we transform each element into a integer using map. Finally, we convert the map into a list and append it to a list of rows. The first array is created using this list of rows.
rows = []
for _ in range(n):
    rows.append(list(map(int, input().split())))
a = np.array(rows)

# We use the same logic to create the second array
rows = []
for _ in range(n):
    rows.append(list(map(int, input().split())))
b = np.array(rows)


# We perform element-wise operations. This means that if the operation is performed between 2 NxM ndarrays, the resulting arrays will also be NxM.
print(np.add(a, b))         # Add operation
print(np.subtract(a, b))    # Subtract operation
print(np.multiply(a, b))    # Multiply operation
print(a // b)               # Integer division operation
print(a % b)                # Mod operation
print(np.power(a, b))       # Power operation

## Sum and Prod

![](imgs\sum_and_prod.png)

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import numpy as np

# We read the number of rows and columns as usual
n, m = list(map(int, input().split()))

# We use a for loop to read n lines from input. Each line will contain M elements. As we use input, firstly we need to convert the string read into a list containing the elements. Secondly, we transform each element into an integer using map. Finally, we convert the map into a list and append it to a list of rows. The first array is created using this list of rows.
rows = []
for _ in range(n):
    rows.append(list(map(int, input().split())))
a = np.array(rows)

# In this statement, we first compute the sum of array along the first dimension. If a = [1 2], [3 4] and axis = 0, the 2x2 array will result in a 1x2 array as follows [1 + 3, 2 + 4] = [4, 6].
# Finally we apply prod to [4, 6] which returns 4 * 6 = 24
print(np.prod(np.sum(a, axis = 0)))

## Polynomials

![](imgs\polynomials.png)

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import numpy as np

# We read the coefficients and put them in a list. This time, as the coefficients may be float numbers we convert the input elements to float
coefficients_list = list(map(float, input().split()))
x = float(input())

# As we are given the coefficients and the value of the 'x', our task is to find out the value of the polynomial. Thus polyval is right tool to use
print(np.polyval(coefficients_list, x))

## Min and Max

![](imgs\min_and_max.png)

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import numpy as np

# We read the number of rows and columns from the input as usual
n, m = list(map(int, input().split()))

# We use a for loop to read n lines from input. Each line will contain M elements. As we use input, firstly we need to convert the string read into a list containing the elements. Secondly, we transform each element into an integer using map. Finally, we convert the map into a list and append it to a list of rows. The array is created using this list of rows.
rows = []
for _ in range(n):
    rows.append(list(map(int, input().split())))
array = np.array(rows)

# We find the minimun value along axis 1. It will return a N, shaped array from which we calculate the max value.
print(np.max(np.min(array, axis = 1)))

## Mean, Var, and Std

![](imgs\mean_var_std.png)
![](imgs\mean_var_std_2.png)

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import numpy as np

# We read the number of rows and columns from the input as usual
n, m = list(map(int, input().split()))

# We use a for loop to read n lines from input. Each line will contain M elements. As we use input, firstly we need to convert the string read into a list containing the elements. Secondly, we transform each element into an integer using map. Finally, we convert the map into a list and append it to a list of rows. The array is created using this list of rows.
rows = []
for _ in range(n):
    rows.append(list(map(int, input().split())))
array = np.array(rows)

print(np.mean(array, axis = 1))  # Calcutate the arithmetic mean along axis 1
print(np.var(array, axis = 0))   # Calcutate the variance along axis 0

# Please note I use round to limit the number of decimals in the return of std. By default, in my case the value returned by std is 1.118033988749895, which is correct byt does not match the length of the desired output: 1.11803398875. That why I use round to limit the output to 11 decimals.
print(round(np.std(array), 11))